Repository Coffee-ing/Client, pull requests merged in 2023-11, with the labels that each got.

#6 [feat] 홈 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coffeeing/client/domain/model/Coffeeing.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeCoffeeingAdapter.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeSortBottomSheetDialog.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeViewModel.kt
  app/src/main/java/com/coffeeing/client/presentation/type/HomeSortType.kt
  app/src/main/java/com/coffeeing/client/util/binding/BindingBottomSheetDialogFragment.kt
  app/src/main/res/color/selector_coffeeing_sort.xml
  app/src/main/res/color/selector_coffeeing_type_filter_background.xml
  app/src/main/res/color/selector_coffeeing_type_text_color.xml
  app/src/main/res/drawable/coffeeing_dummy.png
  app/src/main/res/drawable/coffeeing_gray.png
  app/src/main/res/drawable/coffeeing_logo.png
  app/src/main/res/drawable/ic_home_check.xml
  app/src/main/res/drawable/ic_home_dropdown.xml
  app/src/main/res/drawable/ic_home_fill_heart.xml
  app/src/main/res/drawable/ic_home_location.xml
  app/src/main/res/drawable/ic_home_person.xml
  app/src/main/res/drawable/ic_home_search.xml
  app/src/main/res/drawable/ic_home_stroke_heart.xml
  app/src/main/res/drawable/ic_home_time.xml
  app/src/main/res/drawable/my_page.png
  app/src/main/res/drawable/rect_point_1_radius_15.xml
  app/src/main/res/drawable/rect_point_1_stroke_radius_15.xml
  app/src/main/res/drawable/rect_point_3_radius_15.xml
  app/src/main/res/drawable/shape_border_top_radius_15.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/dialog_bottom_home_sort.xml
  app/src/main/res/layout/item_home_coffeeing.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💫 feat 💫, 🐸 지현 🐸

#5 [Feat] 주최하기 뷰 구현
  .idea/git_toolbox_prj.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coffeeing/client/presentation/dummy/create/CreateActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/dummy/create/DatePickerFragment.kt
  app/src/main/res/drawable/button_selector.xml
  app/src/main/res/drawable/button_selector_clicked.xml
  app/src/main/res/drawable/custom_button_background.xml
  app/src/main/res/drawable/edit_text_border.xml
  app/src/main/res/drawable/ic_back_arrow_white_24.xml
  app/src/main/res/drawable/ic_calendar_maincolor_24.xml
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ➕ add ➕, 🙏 help wanted 🙏, 🧢 호연 🧢

#10 [chore] 커핑 작성 뷰 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coffeeing/client/presentation/create/CreateActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/create/DatePickerFragment.kt
  app/src/main/java/com/coffeeing/client/presentation/dummy/create/CreateActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeActivity.kt
  app/src/main/java/com/coffeeing/client/util/binding/BindingCoffeeingDialogFragment.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_back_arrow_white_24.xml
  app/src/main/res/drawable/ic_calendar_maincolor_24.xml
  app/src/main/res/drawable/ic_create_calendar.xml
  app/src/main/res/drawable/rect_point_1_stroke_radius_5.xml
  app/src/main/res/drawable/rect_radius_10.xml
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/layout/dialog_coffeeing.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✂️ chore ✂️, 🐸 지현 🐸

#7 [feat] 상세페이지 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailButton.kt
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailButtonAdapter.kt
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailButtonViewHolder.kt
  app/src/main/res/drawable/custom_button_background.xml
  app/src/main/res/drawable/ic_detail_back_arrow.xml
  app/src/main/res/drawable/ic_detail_empty_favorite_.xml
  app/src/main/res/drawable/ic_detail_full_favorite.xml
  app/src/main/res/drawable/ic_detail_full_favorite_1.xml
  app/src/main/res/drawable/ic_detail_like_button_selector.xml
  app/src/main/res/drawable/ic_detail_loaction.xml
  app/src/main/res/drawable/ic_detail_person.xml
  app/src/main/res/drawable/ic_detail_time.xml
  app/src/main/res/drawable/like_button_selector.xml
  app/src/main/res/drawable/like_button_selector_clicked.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_detail_button.xml
Labels: ➕ add ➕, 🙏 help wanted 🙏, 🧢 호연 🧢

#13 [init] 서버통신 기초세팅
  app/build.gradle
  app/src/main/java/com/coffeeing/client/data/interceptor/CoffeeingInterceptor.kt
  app/src/main/java/com/coffeeing/client/di/NetworkModule.kt
Labels: 🔅 init 🔅, 🐸 지현 🐸

#15 [feat] Splash 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coffeeing/client/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/img_coffeeing_splash.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimens.xml
Labels: 💫 feat 💫, 🧢 호연 🧢

#9 [feat] 마이페이지 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coffeeing/client/presentation/home/HomeActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/mypage/MypageActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/mypage/MypageCoffeeingAdapter.kt
  app/src/main/java/com/coffeeing/client/presentation/mypage/MypageViewModel.kt
  app/src/main/java/com/coffeeing/client/presentation/mypage/RecyclerViewDecoration.kt
  app/src/main/res/drawable/ib_mypage_back_arrow.xml
  app/src/main/res/drawable/oval_point_1_radius_15.xml
  app/src/main/res/drawable/rect_background_radius_15.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/item_home_coffeeing.xml
  app/src/main/res/layout/item_mypage_coffeeing.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💫 feat 💫, 🐸 지현 🐸, 🧢 호연 🧢

#20 [feat] 신청하기 api 연동
  app/src/main/java/com/coffeeing/client/data/datasource/remote/MainDataSource.kt
  app/src/main/java/com/coffeeing/client/data/model/response/ResponseRegistration.kt
  app/src/main/java/com/coffeeing/client/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/coffeeing/client/data/service/MainService.kt
  app/src/main/java/com/coffeeing/client/domain/model/Registration.kt
  app/src/main/java/com/coffeeing/client/domain/repository/MainRepository.kt
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailViewModel.kt
Labels: 💫 feat 💫, 🐸 지현 🐸

#22 [fix] 상세페이지 내용이 안 보이는 이슈 해결
  app/src/main/java/com/coffeeing/client/presentation/detail/DetailActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/mypage/MypageActivity.kt
Labels: 🔨 fix 🔨, 🐸 지현 🐸

#24 [feat] 검색, 정렬, 필터링 api 연동
  app/src/main/java/com/coffeeing/client/data/datasource/remote/MainDataSource.kt
  app/src/main/java/com/coffeeing/client/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/coffeeing/client/data/service/MainService.kt
  app/src/main/java/com/coffeeing/client/domain/repository/MainRepository.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeActivity.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeSortBottomSheetDialog.kt
  app/src/main/java/com/coffeeing/client/presentation/home/HomeViewModel.kt
  app/src/main/java/com/coffeeing/client/presentation/type/HomeSortType.kt
  app/src/main/res/layout/activity_home.xml
Labels: 💫 feat 💫, 🐸 지현 🐸
